CASE 
	WHEN  {Medical\Date Cancer Diagnosis 1} < {Personal\P DOB} THEN 'Cancer Diagnosis 1 before DOB'
	WHEN  {Medical\Date Cancer Diagnosis 2} < {Personal\P DOB} THEN 'Cancer Diagnosis 2 before DOB'
	WHEN  {Medical\Date Cancer Diagnosis 3} < {Personal\P DOB} THEN 'Cancer Diagnosis 3 before DOB'
	WHEN  {Medical\Date Cancer Diagnosis 4} < {Personal\P DOB} THEN 'Cancer Diagnosis 4 before DOB'
	WHEN  {Medical\Date Cancer Diagnosis 1} > {Personal\P DOD} THEN 'Cancer Diagnosis 1 after DOD'
	WHEN  {Medical\Date Cancer Diagnosis 2} > {Personal\P DOD} THEN 'Cancer Diagnosis 2 after DOD'
	WHEN  {Medical\Date Cancer Diagnosis 3} > {Personal\P DOD} THEN 'Cancer Diagnosis 3 after DOD'
	WHEN  {Medical\Date Cancer Diagnosis 4} > {Personal\P DOD} THEN 'Cancer Diagnosis 4 after DOD'
    WHEN  {Medical\Date Cancer Diagnosis 1} = {Personal\P DOB} THEN 'Cancer Diagnosis 1 same as DOB'
	WHEN  {Medical\Date Cancer Diagnosis 2} = {Personal\P DOB} THEN 'Cancer Diagnosis 2 same as DOB'
	WHEN  {Medical\Date Cancer Diagnosis 3} = {Personal\P DOB} THEN 'Cancer Diagnosis 3 same as DOB'
	WHEN  {Medical\Date Cancer Diagnosis 4} = {Personal\P DOB} THEN 'Cancer Diagnosis 4 same as DOB'
	WHEN  {Medical\Date Cancer Diagnosis 1} = {Personal\P DOD} THEN 'Cancer Diagnosis 1 same as DOD'
	WHEN  {Medical\Date Cancer Diagnosis 2} = {Personal\P DOD} THEN 'Cancer Diagnosis 2 same as DOD'
	WHEN  {Medical\Date Cancer Diagnosis 3} = {Personal\P DOD} THEN 'Cancer Diagnosis 3 same as DOD'
	WHEN  {Medical\Date Cancer Diagnosis 4} = {Personal\P DOD} THEN 'Cancer Diagnosis 4 same as DOD'
ELSE 'OK'
END
