#PRACTICAL - Ethnicity
CASE
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other White'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White and Asian'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White and Black African'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White and Black Caribbean'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other Mixed'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other Asian'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other Black'
	 OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Refused'
	 OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other (please specify)'
THEN '0'
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White British'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White Irish'
	 OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White Jewish Ashkenazi'
THEN '1'
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Chinese'
THEN '2'
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Indian'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Pakistani'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Bangladeshi'
THEN '6'
WHEN IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Black African'
THEN '7'
WHEN IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Black Caribbean'
THEN '8'
WHEN IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Unknown'
THEN 'U'
END
