CASE
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White British'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White Irish'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other White'
THEN 'White'
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White Jewish Ashkenazi'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White and Asian'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White and Black African'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'White and Black Caribbean'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other Mixed'
THEN 'Mixed'
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Indian'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Pakistani'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Bangladeshi'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other Asian'
THEN 'Asian'
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Black Caribbean'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Black African'
     OR IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Other Black'
THEN 'Asian'
WHEN    IFNULL({Personal\P Ethnicity},'x',{Personal\P Ethnicity}) = 'Chinese'
THEN 'Chinese'
ELSE 'U'
END
